name: "tsc"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Run TSC
        run: npx tsc
